# Generated by Django 5.1.7 on 2025-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamApp', '0004_remove_admin_admin_id_remove_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
